"""empty message

Revision ID: 245722b915bf
Revises: 
Create Date: 2021-07-09 21:07:16.040548

"""
from alembic import op
import sqlalchemy as sa


# revision identifiers, used by Alembic.
revision = '245722b915bf'
down_revision = None
branch_labels = None
depends_on = None


def upgrade():
    # ### commands auto generated by Alembic - please adjust! ###
    pass
    # ### end Alembic commands ###


def downgrade():
    # ### commands auto generated by Alembic - please adjust! ###
    pass
    # ### end Alembic commands ###
