#!/bin/bash

set -o errexit
set -o nounset

# celery -A main.celery worker --loglevel=info

watchfiles \
  --filter python \
  'celery -A main.celery worker --loglevel=info -Q high_priority,default'

